export enum APPLICATION_STATUS{
    PENDING = 'PENDING',
    ACCEPTED = 'ACCEPTED',
    UNDER_REVIEW = 'UNDER_REVIEW',
    SHORTLISTED = 'SHORTLISTED',
    REJECTED = 'REJECTED',
    INTERVIEW = 'INTERVIEW'
}